### ISSUE TITLE
Addon stopped working

### ISSUE THREAD

**Issue by ScyllaHide** [kurtextrem/Twitch5#10]
Since like yesterday, the addon stopped working.

(Opera, Win10x64Pro)

Thats what i got as error message: **Channel with the specified name does not exist. Perhaps you typed the wrong address.**
Get this message on all channels i click on.

Any Ideas how to fix it? Or requires it more additional investigation?

Thanks,
SH

**Comment by kurtextrem** [comment]
Please us this: https://chrome.google.com/webstore/detail/alternate-player-for-twit/bhplkbgoehhhddaoolmakpocnenplmhf
