### ISSUE TITLE
Add input field to allow custom scripts (Better TTV etc)

### ISSUE THREAD

**Issue by kurtextrem** [kurtextrem/Twitch5#2]
The reason why I've removed this is, because it could be a reason for getting removed from the Webstore. So the solution is to add an input field that simply loads those scripts.

**Comment by CodyMKW** [comment]
don't know if you knew but Twitch 5 is back on the webstore it only got remove cause the name here it is https://chrome.google.com/webstore/detail/alternate-player-for-twit/bhplkbgoehhhddaoolmakpocnenplmhf

**Comment by kurtextrem** [comment]
Oh cool, didn't notice. I guess in that case we can see my extension
deprecated again as I don't want to "steal" users from him.

Thank you for the notification!

Am 07.03.2018 2:38 nachm. schrieb "Cody Brown" <notifications@github.com>:
